export default {
    "language": "language",
    "zhCN": "Simplified chinese",
    "zhTW": "Fan'ti chinese",
    "enUS": "English",
    "jaJP": "Japanese",
    "koKR": "Korean",
    "rotation": "Rotation",
    "windMode": "Wind Mode",
    "upDown": "up/down",
    "leftRight": "left/right",
    "threeD": "3D",
    "cancle": "stop",
    "sleep": "sleep",
    "natural": "natural",
    "normal": "normal",
    "eco": "ECO",
    "device": "device",
    "addDevice": "Add device",
    "add": "Add",
    "rename": "RENAME",
    "delete": "DELETE",
    "name": "Name",
    "confirm": "CONFIRM",
    "enterDeviceName": "Please enter the device name",
    "selectDeviceTip": "Please select the device first",
    "openDeviceTip": "Please turn on the device first",
    "next": "Next",
    "skip": "Skip",
    "finish": "Finish",
    "previous": "Previous",
    "step1": "First, add the device. Go to the add device page",
    "step2": "After adding the device successfully, wake up the pop-up window and select the device to control",
    "step3": "Tutn on device switch",
    "sameDevice": "Failed to add the same device name or code",
    "selectDevice": "Select device",
    "tips": "Tips",
    "tipText": "Please complete the operation of adding device within 10 minutes after the device is powered on. Overtime will lead to failure of adding device! Please plug and unplug the power supply again and try again.",
    "iKnow": "I got it",
    "noPrompt": "No more prompts",
    "openBLETip": "Please turn on Bluetooth",
    "noSupportBLEAdv": "Device does not support Bluetooth Advertiser",
    "reminder": "Reminder",
    "reminderTips": "Your trust is very important to us. Please read it fully",
    "reminderSay": "It is hereby explained to you as follows:",
    "agreement": "User agreement",
    "and": "and",
    "privacy": "Privacy agreement",
    "reminderTips1": "1. In order to provide you with relevant functions, we will use necessary information;",
    "reminderTips2": '2. In order to cache data information, we need you to authorize "storage permission", and you have the right to refuse or cancel the authorization;',
    "reminderTips3": '3. In order to provide you with basic Bluetooth control functions, we need you to authorize "Bluetooth permission", and you have the right to refuse or cancel the authorization;',
    "reminderTips4": "4. Without your consent, we will not obtain, share or provide your information from a third party;",
    "agree": "Agree",
    "disagree": "Disagree"
};