export default {
    "language": "언어",
    "zhCN": "중국어",
    "zhTW": "중국어 번체",
    "enUS": "영어",
    "jaJP": "일본어",
    "koKR": "한국어",
    "rotation": "순환",
    "windMode": "모드",
    "upDown": "상하회전",
    "leftRight": "좌우회전",
    "threeD": "입체회전",
    "cancle": "회전정지",
    "sleep": "수면풍",
    "natural": "자연풍",
    "normal": "일반풍",
    "eco": "온도감지",
    "device": "설비",
    "addDevice": "장치 추가",
    "add": "추가",
    "rename": "개명",
    "delete": "삭제",
    "name": "이름",
    "confirm": "확정",
    "enterDeviceName": "장치 이름을 입력하십시오",
    "selectDeviceTip": "우선 장치 선택",
    "openDeviceTip": "우선 설비를 열어 주십시오",
    "next": "다음단계",
    "skip": "건너뛰기",
    "finish": "확인",
    "previous": "이전",
    "step1": "설정을 클릭하고 연결 할 기기를 등록한다.",
    "step2": "기기를 성공적으로 등록하면 [장치선택]을 눌러 기기 선택 후 사용할 수 있습니다. ",
    "step3": "전원 스위치",
    "sameDevice": "장치 이름이나 장치 인코딩이 같거나 새로 증가할 수 없습니다",
    "selectDevice": "장치 선택",
    "tips": "참고",
    "tipText": "제품에 전원을 연결하고 10분 안에 기기를 등록해주세요. 시간이 지나면 기기를 등록/추가할 수 없습니다. 전원을 껏다가 켠 후 다시 시도해주세요.",
    "iKnow": "확인",
    "noPrompt": "힌트 없음",
    "openBLETip": "블루투스 열어주세요.",
    "noSupportBLEAdv": "장치는 블루투스 방송을 지원하지 않습니다",
    "reminder": "알림",
    "reminderTips": "당신 의 신임 은 우리 에 게 매우 중요 하 니 충분히 읽 어 주 십시오",
    "reminderSay": "특별히 아래 와 같이 설명 드 립 니 다.",
    "agreement": "사용자 프로 토 콜",
    "and": "하고",
    "privacy": "프라이버시 정책",
    "reminderTips1": "1. 귀하 께 관련 기능 을 제공 하기 위해 저 희 는 필요 한 정 보 를 사용 할 것 입 니 다.",
    "reminderTips2": "2. 데이터 정 보 를 캐 시 하기 위해 저 희 는 귀하 께 서 '저장 권한' 을 부여 하 셔 야 합 니 다. 귀 하 는 권한 을 거절 하거나 취소 할 권리 가 있 습 니 다.",
    "reminderTips3": "3. 귀하 께 기본 적 인 블 루 투 스 제어 기능 을 제공 하기 위해 저 희 는 '블 루 투 스 권한' 을 권한 부여 해 야 합 니 다. 귀 하 는 권한 을 거절 하거나 권한 을 취소 할 권리 가 있 습 니 다.",
    "reminderTips4": "4. 귀하 의 동의 없 이 저 희 는 제3자 로부터 귀하 의 정 보 를 얻 거나 공유 하거나 제공 하지 않 습 니 다.",
    "agree": "받다",
    "disagree": "마다 하 다"
};